// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwxOAdBSRRXmFlFona8dwrSlktTm9pyk4',
    appId: '1:830639642449:web:1b918b201bf950edf0a570',
    messagingSenderId: '830639642449',
    projectId: 'tiketpendakianapp',
    authDomain: 'tiketpendakianapp.firebaseapp.com',
    storageBucket: 'tiketpendakianapp.firebasestorage.app',
    measurementId: 'G-J5PWB3HTNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSDVVhCUXr3l0bkr0fsfxwpT8jFV8Fntg',
    appId: '1:830639642449:android:aa0f654a09c7f7cef0a570',
    messagingSenderId: '830639642449',
    projectId: 'tiketpendakianapp',
    storageBucket: 'tiketpendakianapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW9WbYWF800v-zCveFJJZTHz3eB7vcjls',
    appId: '1:830639642449:ios:ec0326339ca14454f0a570',
    messagingSenderId: '830639642449',
    projectId: 'tiketpendakianapp',
    storageBucket: 'tiketpendakianapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW9WbYWF800v-zCveFJJZTHz3eB7vcjls',
    appId: '1:830639642449:ios:ec0326339ca14454f0a570',
    messagingSenderId: '830639642449',
    projectId: 'tiketpendakianapp',
    storageBucket: 'tiketpendakianapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwxOAdBSRRXmFlFona8dwrSlktTm9pyk4',
    appId: '1:830639642449:web:17562518282c9ae5f0a570',
    messagingSenderId: '830639642449',
    projectId: 'tiketpendakianapp',
    authDomain: 'tiketpendakianapp.firebaseapp.com',
    storageBucket: 'tiketpendakianapp.firebasestorage.app',
    measurementId: 'G-D44W0M6B88',
  );
}
